// Chinese character to pinyin mapping table
const PINYIN_MAP: Record<string, string> = {
  '阿': 'a', '哎': 'ai', '安': 'an', '肮': 'ang', '凹': 'ao',
  '八': 'ba', '白': 'bai', '班': 'ban', '帮': 'bang', '包': 'bao',
  '杯': 'bei', '奔': 'ben', '崩': 'beng', '逼': 'bi', '边': 'bian',
  '标': 'biao', '别': 'bie', '宾': 'bin', '兵': 'bing', '波': 'bo',
  '补': 'bu', '擦': 'ca', '猜': 'cai', '参': 'can', '仓': 'cang',
  '操': 'cao', '册': 'ce', '层': 'ceng', '查': 'cha', '差': 'chai',
  '产': 'chan', '长': 'chang', '超': 'chao', '车': 'che', '沉': 'chen',
  '成': 'cheng', '吃': 'chi', '充': 'chong', '抽': 'chou', '出': 'chu',
  '初': 'chu', '处': 'chu', '川': 'chuan', '创': 'chuang', '吹': 'chui',
  '春': 'chun', '词': 'ci', '从': 'cong', '粗': 'cu', '存': 'cun',
  '村': 'cun', '错': 'cuo', '搭': 'da', '大': 'da', '呆': 'dai',
  '代': 'dai', '带': 'dai', '单': 'dan', '当': 'dang', '刀': 'dao',
  '到': 'dao', '道': 'dao', '的': 'de', '得': 'de', '灯': 'deng',
  '低': 'di', '地': 'di', '第': 'di', '点': 'dian', '电': 'dian',
  '店': 'dian', '掉': 'diao', '调': 'diao', '定': 'ding', '丢': 'diu',
  '东': 'dong', '冬': 'dong', '动': 'dong', '都': 'dou', '读': 'du',
  '短': 'duan', '段': 'duan', '对': 'dui', '队': 'dui', '多': 'duo',
  '额': 'e', '恩': 'en', '儿': 'er', '而': 'er', '耳': 'er',
  '二': 'er', '发': 'fa', '法': 'fa', '翻': 'fan', '反': 'fan',
  '饭': 'fan', '方': 'fang', '房': 'fang', '放': 'fang', '飞': 'fei',
  '非': 'fei', '分': 'fen', '风': 'feng', '封': 'feng', '夫': 'fu',
  '服': 'fu', '父': 'fu', '付': 'fu', '副': 'fu', '复': 'fu',
  '该': 'gai', '改': 'gai', '干': 'gan', '感': 'gan', '刚': 'gang',
  '高': 'gao', '告': 'gao', '哥': 'ge', '歌': 'ge', '个': 'ge',
  '各': 'ge', '给': 'gei', '根': 'gen', '更': 'geng', '工': 'gong',
  '公': 'gong', '功': 'gong', '共': 'gong', '狗': 'gou', '够': 'gou',
  '姑': 'gu', '古': 'gu', '股': 'gu', '顾': 'gu', '瓜': 'gua',
  '挂': 'gua', '关': 'guan', '观': 'guan', '官': 'guan', '管': 'guan',
  '光': 'guang', '广': 'guang', '归': 'gui', '规': 'gui', '鬼': 'gui',
  '贵': 'gui', '国': 'guo', '果': 'guo', '过': 'guo', '还': 'hai',
  '海': 'hai', '害': 'hai', '喊': 'han', '汉': 'han', '好': 'hao',
  '号': 'hao', '喝': 'he', '和': 'he', '河': 'he', '黑': 'hei',
  '很': 'hen', '红': 'hong', '后': 'hou', '候': 'hou', '乎': 'hu',
  '呼': 'hu', '湖': 'hu', '虎': 'hu', '互': 'hu', '户': 'hu',
  '花': 'hua', '华': 'hua', '画': 'hua', '话': 'hua', '化': 'hua',
  '坏': 'huai', '欢': 'huan', '环': 'huan', '换': 'huan', '黄': 'huang',
  '回': 'hui', '会': 'hui', '婚': 'hun', '活': 'huo', '火': 'huo',
  '或': 'huo', '机': 'ji', '鸡': 'ji', '基': 'ji', '及': 'ji',
  '吉': 'ji', '极': 'ji', '急': 'ji', '集': 'ji', '几': 'ji',
  '己': 'ji', '计': 'ji', '记': 'ji', '技': 'ji', '际': 'ji',
  '济': 'ji', '继': 'ji', '加': 'jia', '家': 'jia', '价': 'jia',
  '假': 'jia', '架': 'jia', '坚': 'jian', '间': 'jian', '检': 'jian',
  '简': 'jian', '见': 'jian', '件': 'jian', '建': 'jian', '健': 'jian',
  '将': 'jiang', '江': 'jiang', '讲': 'jiang', '奖': 'jiang', '交': 'jiao',
  '教': 'jiao', '叫': 'jiao', '接': 'jie', '街': 'jie', '节': 'jie',
  '结': 'jie', '姐': 'jie', '解': 'jie', '介': 'jie', '界': 'jie',
  '今': 'jin', '金': 'jin', '仅': 'jin', '进': 'jin', '近': 'jin',
  '京': 'jing', '经': 'jing', '精': 'jing', '井': 'jing', '景': 'jing',
  '静': 'jing', '镜': 'jing', '九': 'jiu', '酒': 'jiu', '旧': 'jiu',
  '就': 'ju', '局': 'ju', '句': 'ju', '决': 'jue', '觉': 'jue',
  '军': 'jun', '卡': 'ka', '开': 'kai', '看': 'kan', '考': 'kao',
  '科': 'ke', '可': 'ke', '克': 'ke', '客': 'ke', '课': 'ke',
  '空': 'kong', '口': 'kou', '哭': 'ku', '苦': 'ku', '快': 'kuai',
  '款': 'kuan', '况': 'kuang', '困': 'kun', '扩': 'kuo', '拉': 'la',
  '来': 'lai', '兰': 'lan', '蓝': 'lan', '浪': 'lang', '老': 'lao',
  '乐': 'le', '了': 'le', '累': 'lei', '冷': 'leng', '里': 'li',
  '理': 'li', '力': 'li', '历': 'li', '利': 'li', '例': 'li',
  '连': 'lian', '脸': 'lian', '练': 'lian', '良': 'liang', '两': 'liang',
  '亮': 'liang', '辆': 'liang', '料': 'liao', '列': 'lie', '林': 'lin',
  '临': 'lin', '零': 'ling', '领': 'ling', '另': 'ling', '流': 'liu',
  '六': 'liu', '龙': 'long', '楼': 'lou', '路': 'lu', '旅': 'lv',
  '律': 'lv', '绿': 'lv', '乱': 'luan', '论': 'lun', '落': 'luo',
  '妈': 'ma', '麻': 'ma', '马': 'ma', '吗': 'ma', '买': 'mai',
  '卖': 'mai', '满': 'man', '忙': 'mang', '毛': 'mao', '冒': 'mao',
  '没': 'mei', '美': 'mei', '妹': 'mei', '门': 'men', '梦': 'meng',
  '米': 'mi', '密': 'mi', '棉': 'mian', '面': 'mian', '苗': 'miao',
  '秒': 'miao', '民': 'min', '明': 'ming', '名': 'ming', '命': 'ming',
  '母': 'mu', '目': 'mu', '木': 'mu', '那': 'na', '哪': 'na',
  '男': 'nan', '南': 'nan', '难': 'nan', '脑': 'nao', '内': 'nei',
  '能': 'neng', '你': 'ni', '年': 'nian', '念': 'nian', '鸟': 'niao',
  '牛': 'niu', '农': 'nong', '女': 'nv', '暖': 'nuan', '怕': 'pa',
  '拍': 'pai', '排': 'pai', '派': 'pai', '盘': 'pan', '跑': 'pao',
  '配': 'pei', '朋': 'peng', '批': 'pi', '片': 'pian', '票': 'piao',
  '品': 'pin', '平': 'ping', '瓶': 'ping', '破': 'po', '七': 'qi',
  '期': 'qi', '其': 'qi', '齐': 'qi', '奇': 'qi', '起': 'qi',
  '气': 'qi', '汽': 'qi', '前': 'qian', '钱': 'qian', '强': 'qiang',
  '桥': 'qiao', '切': 'qie', '亲': 'qin', '轻': 'qing', '清': 'qing',
  '情': 'qing', '请': 'qing', '球': 'qiu', '区': 'qu', '去': 'qu',
  '全': 'quan', '确': 'que', '群': 'qun', '然': 'ran', '让': 'rang',
  '热': 're', '人': 'ren', '认': 'ren', '日': 'ri', '容': 'rong',
  '如': 'ru', '入': 'ru', '三': 'san', '散': 'san', '色': 'se',
  '沙': 'sha', '山': 'shan', '伤': 'shang', '商': 'shang', '上': 'shang',
  '少': 'shao', '设': 'she', '社': 'she', '身': 'shen', '深': 'shen',
  '什': 'shen', '神': 'shen', '生': 'sheng', '声': 'sheng', '省': 'sheng',
  '师': 'shi', '十': 'shi', '石': 'shi', '时': 'shi', '识': 'shi',
  '实': 'shi', '食': 'shi', '史': 'shi', '始': 'shi', '世': 'shi',
  '市': 'shi', '事': 'shi', '视': 'shi', '试': 'shi', '室': 'shi',
  '收': 'shou', '手': 'shou', '首': 'shou', '受': 'shou', '售': 'shou',
  '书': 'shu', '输': 'shu', '数': 'shu', '双': 'shuang', '谁': 'shui',
  '水': 'shui', '顺': 'shun', '说': 'shuo', '思': 'si', '死': 'si',
  '四': 'si', '似': 'si', '送': 'song', '搜': 'sou', '速': 'su',
  '宿': 'su', '算': 'suan', '虽': 'sui', '岁': 'sui', '损': 'sun',
  '所': 'suo', '他': 'ta', '她': 'ta', '它': 'ta', '台': 'tai',
  '太': 'tai', '谈': 'tan', '汤': 'tang', '堂': 'tang', '糖': 'tang',
  '躺': 'tang', '特': 'te', '疼': 'teng', '题': 'ti', '体': 'ti',
  '天': 'tian', '田': 'tian', '条': 'tiao', '跳': 'tiao', '听': 'ting',
  '停': 'ting', '通': 'tong', '同': 'tong', '头': 'tou', '图': 'tu',
  '土': 'tu', '团': 'tuan', '推': 'tui', '退': 'tui', '外': 'wai',
  '完': 'wan', '玩': 'wan', '晚': 'wan', '万': 'wan', '王': 'wang',
  '网': 'wang', '忘': 'wang', '望': 'wang', '危': 'wei', '微': 'wei',
  '为': 'wei', '围': 'wei', '伟': 'wei', '位': 'wei', '味': 'wei',
  '胃': 'wei', '文': 'wen', '问': 'wen', '我': 'wo', '五': 'wu',
  '午': 'wu', '武': 'wu', '物': 'wu', '务': 'wu', '西': 'xi',
  '希': 'xi', '息': 'xi', '习': 'xi', '喜': 'xi', '系': 'xi',
  '细': 'xi', '下': 'xia', '夏': 'xia', '先': 'xian', '鲜': 'xian',
  '现': 'xian', '线': 'xian', '乡': 'xiang', '相': 'xiang', '香': 'xiang',
  '想': 'xiang', '向': 'xiang', '象': 'xiang', '像': 'xiang', '小': 'xiao',
  '校': 'xiao', '笑': 'xiao', '些': 'xie', '写': 'xie', '谢': 'xie',
  '心': 'xin', '新': 'xin', '信': 'xin', '星': 'xing', '行': 'xing',
  '形': 'xing', '性': 'xing', '姓': 'xing', '兄': 'xiong', '休': 'xiu',
  '修': 'xiu', '须': 'xu', '需': 'xu', '许': 'xu', '选': 'xuan',
  '学': 'xue', '雪': 'xue', '血': 'xue', '寻': 'xun', '呀': 'ya',
  '牙': 'ya', '烟': 'yan', '言': 'yan', '研': 'yan', '眼': 'yan',
  '演': 'yan', '验': 'yan', '羊': 'yang', '阳': 'yang', '样': 'yang',
  '要': 'yao', '药': 'yao', '爷': 'ye', '也': 'ye', '业': 'ye',
  '夜': 'ye', '一': 'yi', '衣': 'yi', '医': 'yi', '已': 'yi',
  '以': 'yi', '亿': 'yi', '易': 'yi', '意': 'yi', '因': 'yin',
  '音': 'yin', '银': 'yin', '应': 'ying', '英': 'ying', '影': 'ying',
  '用': 'you', '由': 'you', '油': 'you', '游': 'you', '友': 'you',
  '有': 'you', '又': 'you', '右': 'you', '鱼': 'yu', '于': 'yu',
  '余': 'yu', '雨': 'yu', '语': 'yu', '育': 'yu', '元': 'yuan',
  '园': 'yuan', '原': 'yuan', '远': 'yuan', '院': 'yuan', '愿': 'yuan',
  '月': 'yue', '越': 'yue', '云': 'yun', '运': 'yun', '杂': 'za',
  '在': 'zai', '早': 'zao', '造': 'zao', '则': 'ze', '怎': 'zen',
  '增': 'zeng', '展': 'zhan', '站': 'zhan', '张': 'zhang', '长2': 'zhang',
  '找': 'zhao', '照': 'zhao', '者': 'zhe', '这': 'zhe', '真': 'zhen',
  '整': 'zheng', '正': 'zheng', '政': 'zheng', '之': 'zhi', '支': 'zhi',
  '知': 'zhi', '直': 'zhi', '只': 'zhi', '纸': 'zhi', '指': 'zhi',
  '至': 'zhi', '志': 'zhi', '制': 'zhi', '治': 'zhi', '中': 'zhong',
  '钟': 'zhong', '种': 'zhong', '重': 'zhong', '众': 'zhong', '州': 'zhou',
  '周': 'zhou', '洲': 'zhou', '主': 'zhu', '住': 'zhu', '注': 'zhu',
  '祝': 'zhu', '专': 'zhuan', '转': 'zhuan', '装': 'zhuang', '状': 'zhuang',
  '准': 'zhun', '桌': 'zhuo', '子': 'zi', '自': 'zi', '字': 'zi',
  '走': 'zou', '租': 'zu', '足': 'zu', '族': 'zu', '组': 'zu',
  '嘴': 'zui', '最': 'zui', '罪': 'zui', '做': 'zuo', '作': 'zuo',
  '坐': 'zuo', '座': 'zuo',
};

// Get the pinyin for a single Chinese character
function getCharPinyin(char: string): string {
  if (PINYIN_MAP[char]) {
    return PINYIN_MAP[char];
  }
  // For non-Chinese characters, return the character itself (lowercased)
  return char.toLowerCase();
}

// Get the first letter of pinyin for a single Chinese character
function getCharFirstLetter(char: string): string {
  const pinyin = getCharPinyin(char);
  return pinyin.charAt(0);
}

// Convert a string to full pinyin (no spaces between syllables)
export function toPinyin(text: string): string {
  if (!text) return '';
  return Array.from(text).map(char => getCharPinyin(char)).join('');
}

// Get the first letters of pinyin for each character
export function getFirstLetter(text: string): string {
  if (!text) return '';
  return Array.from(text).map(char => getCharFirstLetter(char)).join('');
}
